version: '2'

services:

  aem-author:
    container_name: aem-author
    image: aemdesign/aem
    ports:
      - 4502:8080
      - 30303:58242
    volumes:
      - /opt/aem/author/repository:/aem/crx-quickstart/repository
      - /opt/aem/author/logs:/aem/crx-quickstart/logs
      - /opt/aem/author/backup:/aem/backup
    environment:
      - "TZ=Europe/London"    
      - "AEM_RUNMODE=-Dsling.run.modes=author,crx3,crx3tar,dev"
      - "AEM_JVM_OPTS=-server -Xms248m -Xmx1524m -XX:MaxDirectMemorySize=256M -XX:+CMSClassUnloadingEnabled -Djava.awt.headless=true -Dorg.apache.felix.http.host=0.0.0.0 -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=58242,suspend=n" 
      
  aem-publish:
    container_name: aem-publish
    image: aemdesign/aem
    ports:
      - 4503:8080
      - 40404:58242
    volumes:
      - /opt/aem/publish/repository:/aem/crx-quickstart/repository
      - /opt/aem/publish/logs:/aem/crx-quickstart/logs
      - /opt/aem/publish/backup:/aem/backup
    environment:
      - "TZ=Europe/London"    
      - "AEM_RUNMODE=-Dsling.run.modes=publish,crx3,crx3tar,dev"
      - "AEM_JVM_OPTS=-server -Xms248m -Xmx1524m -XX:MaxDirectMemorySize=256M -XX:+CMSClassUnloadingEnabled -Djava.awt.headless=true -Dorg.apache.felix.http.host=0.0.0.0 -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=58242,suspend=n"
      
  aem-publish-dispatcher:
    container_name: aem-publish-dispatcher
    image: aemdesign/dispatcher
    ports:
      - 8080:8080
      - 9433:8433
    volumes:
      - /opt/aem/dispatcher/cache:/data/httpd/cache
      - /opt/aem/dispatcher/logs:/data/httpd/logs
      - /opt/aem/dispatcher/redirectmap:/data/httpd/redirectmap
      - /opt/aem/dispatcher/configs:/dispatcher/publish/configs
    environment:
      - "TZ=Europe/London"    
      - "RENDERER_HOST=172.17.0.1"  
      - "RENDERER_PORT=4503"
      - "DISPATCHER_LOGLEVEL=3"
      - "DISPATCHER_CONFIG=publish"
